/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /root/remedias/nim/nimcache/stdlib_sharedlist.o /root/remedias/nim/nimcache/stdlib_sharedlist.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef long tyArray_xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAlocks)(pthread_mutex_t* lock);
N_LIB_PRIVATE N_NIMCALL(void, acquire_c9cbvs4ShkxrwmQmnY63PGA)(pthread_mutex_t* lock);
N_LIB_PRIVATE N_NOCONV(void*, allocShared0_sVm4rDImKK2ZDdylByayiA_3)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, release_c9cbvs4ShkxrwmQmnY63PGA_2)(pthread_mutex_t* lock);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, initLock_NyibMGWEvLI6dmuAjxN9brAlocks)(pthread_mutex_t* lock) {
	pthread_mutex_init(lock, NIM_NIL);
}

N_LIB_PRIVATE N_NIMCALL(void, init_JKeFCoMeAURymbhVJWrpNA)(tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw* t) {
	initLock_NyibMGWEvLI6dmuAjxN9brAlocks((&(*t).lock));
	(*t).head = NIM_NIL;
	(*t).tail = NIM_NIL;
}

N_LIB_PRIVATE N_NIMCALL(void, add_LMD14ZZveJ1hTQDkuvr6bQ)(tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw* x, void* y) {
	tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* node;
	acquire_c9cbvs4ShkxrwmQmnY63PGA((&(*x).lock));
	node = (tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw*)0;
	{
		NIM_BOOL T3_;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((*x).tail == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*(*x).tail).dataLen == ((NI) 100));
		LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = (void*)0;
		T7_ = allocShared0_sVm4rDImKK2ZDdylByayiA_3(((NI) (((NI)sizeof(tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw)))));
		node = ((tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw*) (T7_));
		(*node).next = (*x).tail;
		(*x).tail = node;
		{
			if (!((*x).head == NIM_NIL)) goto LA10_;
			(*x).head = node;
		}
		LA10_: ;
	}
	goto LA1_;
	LA5_: ;
	{
		node = (*x).tail;
	}
	LA1_: ;
	(*node).d[((*node).dataLen)- 0] = y;
	(*node).dataLen += ((NI) 1);
	release_c9cbvs4ShkxrwmQmnY63PGA_2((&(*x).lock));
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistInit000)(void) {
	nimfr_("sharedlist", "sharedlist.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistDatInit000)(void) {
}

