/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /root/remedias/nim/nimcache/stdlib_terminal.o /root/remedias/nim/nimcache/stdlib_terminal.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <termios.h>
#include <string.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyTuple_47w2DboNEPf69aPgubZdd7Q tyTuple_47w2DboNEPf69aPgubZdd7Q;
typedef unsigned char tyArray_wo9atxlj1CQKWeAypuYX9cIg[32];
struct tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA {
unsigned short ws_row;
unsigned short ws_col;
unsigned short ws_xpixel;
unsigned short ws_ypixel;
};
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI tyArray_GAcaPw08Gj9cXYhAaMMr9cfw[1];
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA;
typedef NU8 tyEnum_Style_NXKayqTLMsAibFwNceBlpA;
typedef NU8 tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef NU8 tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA;
struct tyTuple_47w2DboNEPf69aPgubZdd7Q {
NI Field0;
NI Field1;
NI Field2;
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
N_LIB_PRIVATE N_NIMCALL(void, setRaw_bWuPmHcnrBG1QQlDC4s7ug)(int fd, int time_0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2)(NI* fds, NI fdsLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, terminalSize_xv1ti3xUvO9cxOT8Iw8Silg)(void);
N_LIB_PRIVATE N_NIMCALL(void, hideCursor_tFIu39aFSR3N0M64Ynwugng)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, showCursor_tFIu39aFSR3N0M64Ynwugng_2)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(void, setCursorPos_UIoIgoUReHcDarvfaNRl3A)(FILE* f, NI x, NI y);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, add_IbYQ9cTcoQ89aIwM2IEYGMng)(NimStringDesc** result, NI64 x);
N_LIB_PRIVATE N_NIMCALL(void, setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ)(FILE* f, NI x);
N_LIB_PRIVATE N_NIMCALL(void, cursorUp_KTh8Z5dlyNBmCQ1i9aGXTzg)(FILE* f, NI count);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, cursorDown_KTh8Z5dlyNBmCQ1i9aGXTzg_2)(FILE* f, NI count);
N_LIB_PRIVATE N_NIMCALL(void, cursorForward_KTh8Z5dlyNBmCQ1i9aGXTzg_3)(FILE* f, NI count);
N_LIB_PRIVATE N_NIMCALL(void, cursorBackward_KTh8Z5dlyNBmCQ1i9aGXTzg_4)(FILE* f, NI count);
N_LIB_PRIVATE N_NIMCALL(void, eraseLine_tFIu39aFSR3N0M64Ynwugng_3)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(void, eraseScreen_tFIu39aFSR3N0M64Ynwugng_4)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_5)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ)(NI style);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style);
N_LIB_PRIVATE N_NIMCALL(void, writeStyled_jPzCz3P0CaIFIvdlX9aQd4w)(NimStringDesc* txt, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style);
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor_6SjySiY3ji4zTKKPgtXoig)(FILE* f, tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA bg, NIM_BOOL bright);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getFGColorStr_JQuRsZwRGgtcto9at4yRYqw)(NI color);
N_LIB_PRIVATE N_NIMCALL(tyTuple_47w2DboNEPf69aPgubZdd7Q, extractRGB_BBeGhczeu0Oe9b4tbckVIHA)(NI a);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getBGColorStr_JQuRsZwRGgtcto9at4yRYqw_2)(NI color);
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA)(FILE* f, NI color);
N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA_2)(FILE* f, NI color);
N_LIB_PRIVATE N_NIMCALL(void, setTrueColor_cUJ3dLt9bYXmlU3lm9a8z5lA_3)(FILE* f, NI color);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty_POoHvosCWg3Yl5ieYeLHrg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, getch_PZUNldkwV2VhZMU6UCrZTA)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar_ufPUIQ2Rg4xhWjWigciDOg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readPasswordFromStdin_HR8zZ5lRzcgpZhC3TYXnoQ)(NimStringDesc* prompt, NimStringDesc** password);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine_sO1bQXVRA6RP9cdYJXNKeSw)(FILE* f, NimStringDesc** line);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readPasswordFromStdin_ucTCJi9arxLW5NPhud9bqzAA)(NimStringDesc* prompt);
N_LIB_PRIVATE N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isTrueColorSupported_pgygBZbo45KrYv6AmVkHkQ)(void);
N_LIB_PRIVATE N_NIMCALL(void, enableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w)(void);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwasyncdispatch)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQasyncdispatch)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, disableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w_2)(void);
NIM_BOOL trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;
NIM_BOOL trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ;
NIM_BOOL fgSetColor_az9a3BILKewIOic9a2Ah9a4tQ;
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_THREADVAR NI gFG_g7w4T3anr20OMlWloNx2tQ;
NIM_THREADVAR NI gBG_dgmeknpHWrtwqMJGQAp9atA;
NIM_CONST tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw TM_CN3raB9atujkEiPpxYAdlgQ_4 = {((NI) 0),
((NI) 1),
((NI) 2)}
;
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_5, "COLUMNS", 7);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_6, "", 0);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_7, "LINES", 5);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_8, "\033[\?25l", 6);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_9, "\033[\?25h", 6);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_10, "\033[", 2);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_11, ";", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_12, "f", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_13, "G", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_14, "B", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_15, "C", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_16, "D", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_17, "\033[2K", 4);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_18, "\033[2J", 4);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_19, "\033[0m", 4);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_20, "m", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_24, "\033[38;2;", 7);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_25, "\033[48;2;", 7);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_26, "\012", 1);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_30, "truecolor", 9);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_31, "24bit", 5);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_CN3raB9atujkEiPpxYAdlgQ_29 = {((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_30),
((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_31)}
;
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_32, "COLORTERM", 9);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, setRaw_bWuPmHcnrBG1QQlDC4s7ug)(int fd, int time_0) {
	struct termios mode;
	int T1_;
	int T2_;
	nimfr_("setRaw", "terminal.nim");
	memset((void*)(&mode), 0, sizeof(mode));
	nimln_(212, "terminal.nim");
	T1_ = (int)0;
	T1_ = tcgetattr(fd, (&mode));
	T1_;
	nimln_(213, "terminal.nim");
	mode.c_iflag = (NU32)(mode.c_iflag & (NU32)((NU32) ~((NU32)((NU32)((NU32)((NU32)(BRKINT | ICRNL) | INPCK) | ISTRIP) | IXON))));
	nimln_(215, "terminal.nim");
	mode.c_oflag = (NU32)(mode.c_oflag & (NU32)((NU32) ~(OPOST)));
	nimln_(216, "terminal.nim");
	mode.c_cflag = (NU32)((NU32)(mode.c_cflag & (NU32)((NU32) ~((NU32)(CSIZE | PARENB)))) | CS8);
	nimln_(217, "terminal.nim");
	mode.c_lflag = (NU32)(mode.c_lflag & (NU32)((NU32) ~((NU32)((NU32)((NU32)(ECHO | ICANON) | IEXTEN) | ISIG))));
	if ((NU)(VMIN) > (NU)(31)) raiseIndexError();
	nimln_(218, "terminal.nim");
	mode.c_cc[(VMIN)- 0] = 1;
	if ((NU)(VTIME) > (NU)(31)) raiseIndexError();
	nimln_(219, "terminal.nim");
	mode.c_cc[(VTIME)- 0] = 0;
	nimln_(220, "terminal.nim");
	T2_ = (int)0;
	T2_ = tcsetattr(fd, time_0, (&mode));
	T2_;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0) {
	NI result;
	tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;
	nimfr_("terminalWidthIoctl", "terminal.nim");
{	result = (NI)0;
	memset((void*)(&win), 0, sizeof(win));
	{
		NI fd;
		NI i;
		fd = (NI)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_2;
				if (!(i < fdsLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(fdsLen_0)) raiseIndexError();
				fd = fds[i];
				nimln_(227, "terminal.nim");
				{
					NI T6_;
					nimln_(398, "system.nim");
					nimln_(227, "terminal.nim");
					T6_ = (NI)0;
					T6_ = ioctl(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), TIOCGWINSZ, (&win));
					if (!!((T6_ == ((NI) -1)))) goto LA7_;
					nimln_(228, "terminal.nim");
					result = ((NI) (win.ws_col));
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(2188, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_2 = addInt(i, ((NI) 1));
				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_2);
			} LA3: ;
		}
	}
	nimln_(229, "terminal.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2)(NI* fds, NI fdsLen_0) {
	NI result;
	tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;
	nimfr_("terminalHeightIoctl", "terminal.nim");
{	result = (NI)0;
	memset((void*)(&win), 0, sizeof(win));
	{
		NI fd;
		NI i;
		fd = (NI)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_3;
				if (!(i < fdsLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(fdsLen_0)) raiseIndexError();
				fd = fds[i];
				nimln_(236, "terminal.nim");
				{
					NI T6_;
					nimln_(398, "system.nim");
					nimln_(236, "terminal.nim");
					T6_ = (NI)0;
					T6_ = ioctl(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), TIOCGWINSZ, (&win));
					if (!!((T6_ == ((NI) -1)))) goto LA7_;
					nimln_(237, "terminal.nim");
					result = ((NI) (win.ws_row));
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(2188, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_3 = addInt(i, ((NI) 1));
				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_3);
			} LA3: ;
		}
	}
	nimln_(238, "terminal.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void) {
	NI result;
	NI w;
	NimStringDesc* cterm;
	int fd;
	NCSTRING T5_;
	int T11_;
	NimStringDesc* s;
	nimfr_("terminalWidth", "terminal.nim");
{	result = (NI)0;
	nimln_(246, "terminal.nim");
	w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(TM_CN3raB9atujkEiPpxYAdlgQ_4, 3);
	nimln_(247, "terminal.nim");
	{
		if (!(((NI) 0) < w)) goto LA3_;
		result = w;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(248, "terminal.nim");
	cterm = mnewString(((NI)chckRange(L_ctermid, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(249, "terminal.nim");
	T5_ = (NCSTRING)0;
	T5_ = ctermid(cterm->data);
	fd = open(T5_, ((int) 0));
	nimln_(250, "terminal.nim");
	{
		tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
		nimln_(398, "system.nim");
		nimln_(250, "terminal.nim");
		if (!!((fd == ((NI32) -1)))) goto LA8_;
		nimln_(251, "terminal.nim");
		T10_[0] = ((NI) (fd));
		w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(T10_, 1);
	}
	LA8_: ;
	nimln_(252, "terminal.nim");
	T11_ = (int)0;
	T11_ = close(fd);
	T11_;
	nimln_(253, "terminal.nim");
	{
		if (!(((NI) 0) < w)) goto LA14_;
		result = w;
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(254, "terminal.nim");
	s = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_5), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_6));
	nimln_(255, "terminal.nim");
	{
		NIM_BOOL T18_;
		NIM_BOOL T19_;
		NI T21_;
		T18_ = (NIM_BOOL)0;
		T19_ = (NIM_BOOL)0;
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));
		if (!(T19_)) goto LA20_;
		T21_ = (NI)0;
		T21_ = npuParseInt(s, (&w), ((NI) 0));
		T19_ = (((NI) 0) < T21_);
		LA20_: ;
		T18_ = T19_;
		if (!(T18_)) goto LA22_;
		T18_ = (((NI) 0) < w);
		LA22_: ;
		if (!T18_) goto LA23_;
		nimln_(256, "terminal.nim");
		result = w;
		goto BeforeRet_;
	}
	LA23_: ;
	nimln_(257, "terminal.nim");
	result = ((NI) 80);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2)(void) {
	NI result;
	NI h;
	NimStringDesc* cterm;
	int fd;
	NCSTRING T5_;
	int T11_;
	NimStringDesc* s;
	nimfr_("terminalHeight", "terminal.nim");
{	result = (NI)0;
	nimln_(264, "terminal.nim");
	h = terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2(TM_CN3raB9atujkEiPpxYAdlgQ_4, 3);
	nimln_(265, "terminal.nim");
	{
		if (!(((NI) 0) < h)) goto LA3_;
		result = h;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(266, "terminal.nim");
	cterm = mnewString(((NI)chckRange(L_ctermid, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(267, "terminal.nim");
	T5_ = (NCSTRING)0;
	T5_ = ctermid(cterm->data);
	fd = open(T5_, ((int) 0));
	nimln_(268, "terminal.nim");
	{
		tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
		nimln_(398, "system.nim");
		nimln_(268, "terminal.nim");
		if (!!((fd == ((NI32) -1)))) goto LA8_;
		nimln_(269, "terminal.nim");
		T10_[0] = ((NI) (fd));
		h = terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2(T10_, 1);
	}
	LA8_: ;
	nimln_(270, "terminal.nim");
	T11_ = (int)0;
	T11_ = close(fd);
	T11_;
	nimln_(271, "terminal.nim");
	{
		if (!(((NI) 0) < h)) goto LA14_;
		result = h;
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(272, "terminal.nim");
	s = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_6));
	nimln_(273, "terminal.nim");
	{
		NIM_BOOL T18_;
		NIM_BOOL T19_;
		NI T21_;
		T18_ = (NIM_BOOL)0;
		T19_ = (NIM_BOOL)0;
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));
		if (!(T19_)) goto LA20_;
		T21_ = (NI)0;
		T21_ = npuParseInt(s, (&h), ((NI) 0));
		T19_ = (((NI) 0) < T21_);
		LA20_: ;
		T18_ = T19_;
		if (!(T18_)) goto LA22_;
		T18_ = (((NI) 0) < h);
		LA22_: ;
		if (!T18_) goto LA23_;
		nimln_(274, "terminal.nim");
		result = h;
		goto BeforeRet_;
	}
	LA23_: ;
	nimln_(275, "terminal.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, terminalSize_xv1ti3xUvO9cxOT8Iw8Silg)(void) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("terminalSize", "terminal.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(280, "terminal.nim");
	result.Field0 = terminalWidth_Tjr5MOdj42hdx5sjNUiDXw();
	result.Field1 = terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2();
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, hideCursor_tFIu39aFSR3N0M64Ynwugng)(FILE* f) {
	nimfr_("hideCursor", "terminal.nim");
	nimln_(297, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_8));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, showCursor_tFIu39aFSR3N0M64Ynwugng_2)(FILE* f) {
	nimfr_("showCursor", "terminal.nim");
	nimln_(304, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_9));
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, setCursorPos_UIoIgoUReHcDarvfaNRl3A)(FILE* f, NI x, NI y) {
	NimStringDesc* fmtRes;
	nimfr_("setCursorPos", "terminal.nim");
	nimln_(313, "terminal.nim");
	fmtRes = rawNewString(((NI) 51));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 2);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (y)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_11));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (x)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_12));
	write_c4mGyJBvK73pdM22jiweKQ(f, fmtRes);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ)(FILE* f, NI x) {
	NimStringDesc* fmtRes;
	nimfr_("setCursorXPos", "terminal.nim");
	nimln_(328, "terminal.nim");
	fmtRes = rawNewString(((NI) 37));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 2);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (x)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_13));
	write_c4mGyJBvK73pdM22jiweKQ(f, fmtRes);
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(void, cursorUp_KTh8Z5dlyNBmCQ1i9aGXTzg)(FILE* f, NI count) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("cursorUp", "terminal.nim");
	nimln_(355, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(count);
	T1_ = rawNewString(T2_->Sup.len + 3);
appendString(T1_, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
appendString(T1_, T2_);
appendChar(T1_, 65);
	write_c4mGyJBvK73pdM22jiweKQ(f, T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, cursorDown_KTh8Z5dlyNBmCQ1i9aGXTzg_2)(FILE* f, NI count) {
	NimStringDesc* fmtRes;
	nimfr_("cursorDown", "terminal.nim");
	nimln_(365, "terminal.nim");
	fmtRes = rawNewString(((NI) 41));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 2);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (count)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_14));
	write_c4mGyJBvK73pdM22jiweKQ(f, fmtRes);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, cursorForward_KTh8Z5dlyNBmCQ1i9aGXTzg_3)(FILE* f, NI count) {
	NimStringDesc* fmtRes;
	nimfr_("cursorForward", "terminal.nim");
	nimln_(375, "terminal.nim");
	fmtRes = rawNewString(((NI) 41));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 2);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (count)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_15));
	write_c4mGyJBvK73pdM22jiweKQ(f, fmtRes);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, cursorBackward_KTh8Z5dlyNBmCQ1i9aGXTzg_4)(FILE* f, NI count) {
	NimStringDesc* fmtRes;
	nimfr_("cursorBackward", "terminal.nim");
	nimln_(385, "terminal.nim");
	fmtRes = rawNewString(((NI) 41));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 2);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (count)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_16));
	write_c4mGyJBvK73pdM22jiweKQ(f, fmtRes);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, eraseLine_tFIu39aFSR3N0M64Ynwugng_3)(FILE* f) {
	nimfr_("eraseLine", "terminal.nim");
	nimln_(438, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_17));
	nimln_(439, "terminal.nim");
	setCursorXPos_xCTglc09c1SJqpnj2xD1oSQ(f, ((NI) 0));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, eraseScreen_tFIu39aFSR3N0M64Ynwugng_4)(FILE* f) {
	nimfr_("eraseScreen", "terminal.nim");
	nimln_(461, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_18));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_5)(FILE* f) {
	nimfr_("resetAttributes", "terminal.nim");
	nimln_(471, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_19));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ)(NI style) {
	NimStringDesc* result;
	NimStringDesc* fmtRes;
	nimfr_("getStyleStr", "terminal.nim");
	result = (NimStringDesc*)0;
	nimln_(492, "terminal.nim");
	fmtRes = rawNewString(((NI) 41));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 2);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (style)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_20));
	result = copyString(fmtRes);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style) {
	nimfr_("setStyle", "terminal.nim");
	{
		tyEnum_Style_NXKayqTLMsAibFwNceBlpA s;
		NI i;
		s = (tyEnum_Style_NXKayqTLMsAibFwNceBlpA)0;
		nimln_(2219, "system.nim");
		i = ((NI) 1);
		{
			nimln_(2220, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_21;
				if (!(i <= ((NI) 8))) goto LA3;
				nimln_(2221, "system.nim");
				{
					NimStringDesc* T8_;
					if (!((style &(1U<<((NU)((((tyEnum_Style_NXKayqTLMsAibFwNceBlpA)chckRange(i, ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 1), ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 8)))- 1))&7U)))!=0)) goto LA6_;
					s = ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA)chckRange(i, ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 1), ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 8)));
					nimln_(513, "terminal.nim");
					T8_ = (NimStringDesc*)0;
					T8_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(s);
					write_c4mGyJBvK73pdM22jiweKQ(f, T8_);
				}
				LA6_: ;
				nimln_(2222, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_21 = addInt(i, ((NI) 1));
				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_21);
			} LA3: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, writeStyled_jPzCz3P0CaIFIvdlX9aQd4w)(NimStringDesc* txt, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style) {
	nimfr_("writeStyled", "terminal.nim");
	nimln_(523, "terminal.nim");
	setStyle_zEKKPPIjKZs9bVYu4TwenLg(stdout, style);
	nimln_(524, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(stdout, txt);
	nimln_(525, "terminal.nim");
	resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
	nimln_(526, "terminal.nim");
	{
		NimStringDesc* T5_;
		nimln_(398, "system.nim");
		nimln_(526, "terminal.nim");
		if (!!((gFG_g7w4T3anr20OMlWloNx2tQ == ((NI) 0)))) goto LA3_;
		nimln_(527, "terminal.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(gFG_g7w4T3anr20OMlWloNx2tQ);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, T5_);
	}
	LA3_: ;
	nimln_(528, "terminal.nim");
	{
		NimStringDesc* T10_;
		nimln_(398, "system.nim");
		nimln_(528, "terminal.nim");
		if (!!((gBG_dgmeknpHWrtwqMJGQAp9atA == ((NI) 0)))) goto LA8_;
		nimln_(529, "terminal.nim");
		T10_ = (NimStringDesc*)0;
		T10_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(gBG_dgmeknpHWrtwqMJGQAp9atA);
		write_c4mGyJBvK73pdM22jiweKQ(stdout, T10_);
	}
	LA8_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright) {
	NimStringDesc* T5_;
	nimfr_("setForegroundColor", "terminal.nim");
	nimln_(573, "terminal.nim");
	gFG_g7w4T3anr20OMlWloNx2tQ = fg;
	nimln_(574, "terminal.nim");
	{
		NI TM_CN3raB9atujkEiPpxYAdlgQ_22;
		if (!bright) goto LA3_;
		TM_CN3raB9atujkEiPpxYAdlgQ_22 = addInt(gFG_g7w4T3anr20OMlWloNx2tQ, ((NI) 60));
		gFG_g7w4T3anr20OMlWloNx2tQ = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_22);
	}
	LA3_: ;
	nimln_(575, "terminal.nim");
	T5_ = (NimStringDesc*)0;
	T5_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(gFG_g7w4T3anr20OMlWloNx2tQ);
	write_c4mGyJBvK73pdM22jiweKQ(f, T5_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor_6SjySiY3ji4zTKKPgtXoig)(FILE* f, tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA bg, NIM_BOOL bright) {
	NimStringDesc* T5_;
	nimfr_("setBackgroundColor", "terminal.nim");
	nimln_(595, "terminal.nim");
	gBG_dgmeknpHWrtwqMJGQAp9atA = bg;
	nimln_(596, "terminal.nim");
	{
		NI TM_CN3raB9atujkEiPpxYAdlgQ_23;
		if (!bright) goto LA3_;
		TM_CN3raB9atujkEiPpxYAdlgQ_23 = addInt(gBG_dgmeknpHWrtwqMJGQAp9atA, ((NI) 60));
		gBG_dgmeknpHWrtwqMJGQAp9atA = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_23);
	}
	LA3_: ;
	nimln_(597, "terminal.nim");
	T5_ = (NimStringDesc*)0;
	T5_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(gBG_dgmeknpHWrtwqMJGQAp9atA);
	write_c4mGyJBvK73pdM22jiweKQ(f, T5_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getFGColorStr_JQuRsZwRGgtcto9at4yRYqw)(NI color) {
	NimStringDesc* result;
	tyTuple_47w2DboNEPf69aPgubZdd7Q rgb;
	NimStringDesc* fmtRes;
	nimfr_("getFGColorStr", "terminal.nim");
	result = (NimStringDesc*)0;
	nimln_(602, "terminal.nim");
	rgb = extractRGB_BBeGhczeu0Oe9b4tbckVIHA(color);
	nimln_(603, "terminal.nim");
	fmtRes = rawNewString(((NI) 74));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 7);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_24));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field0)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_11));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field1)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_11));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field2)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_20));
	result = copyString(fmtRes);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getBGColorStr_JQuRsZwRGgtcto9at4yRYqw_2)(NI color) {
	NimStringDesc* result;
	tyTuple_47w2DboNEPf69aPgubZdd7Q rgb;
	NimStringDesc* fmtRes;
	nimfr_("getBGColorStr", "terminal.nim");
	result = (NimStringDesc*)0;
	nimln_(614, "terminal.nim");
	rgb = extractRGB_BBeGhczeu0Oe9b4tbckVIHA(color);
	nimln_(615, "terminal.nim");
	fmtRes = rawNewString(((NI) 74));
	nimln_(313, "strformat.nim");
	fmtRes = resizeString(fmtRes, 7);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_25));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field0)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_11));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field1)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_11));
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field2)));
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_20));
	result = copyString(fmtRes);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA)(FILE* f, NI color) {
	nimfr_("setForegroundColor", "terminal.nim");
	nimln_(626, "terminal.nim");
	{
		NimStringDesc* T5_;
		if (!trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ) goto LA3_;
		nimln_(627, "terminal.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = getFGColorStr_JQuRsZwRGgtcto9at4yRYqw(color);
		write_c4mGyJBvK73pdM22jiweKQ(f, T5_);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA_2)(FILE* f, NI color) {
	nimfr_("setBackgroundColor", "terminal.nim");
	nimln_(631, "terminal.nim");
	{
		NimStringDesc* T5_;
		if (!trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ) goto LA3_;
		nimln_(632, "terminal.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = getBGColorStr_JQuRsZwRGgtcto9at4yRYqw_2(color);
		write_c4mGyJBvK73pdM22jiweKQ(f, T5_);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setTrueColor_cUJ3dLt9bYXmlU3lm9a8z5lA_3)(FILE* f, NI color) {
	nimfr_("setTrueColor", "terminal.nim");
	nimln_(635, "terminal.nim");
	{
		if (!fgSetColor_az9a3BILKewIOic9a2Ah9a4tQ) goto LA3_;
		nimln_(636, "terminal.nim");
		setForegroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA(f, color);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(638, "terminal.nim");
		setBackgroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA_2(f, color);
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty_POoHvosCWg3Yl5ieYeLHrg)(FILE* f) {
	NIM_BOOL result;
	int T1_;
	int T2_;
	nimfr_("isatty", "terminal.nim");
	result = (NIM_BOOL)0;
	nimln_(649, "terminal.nim");
	nimln_(398, "system.nim");
	nimln_(649, "terminal.nim");
	T1_ = (int)0;
	T1_ = getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg(f);
	T2_ = (int)0;
	T2_ = isatty(T1_);
	result = !((T2_ == ((NI32) 0)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, getch_PZUNldkwV2VhZMU6UCrZTA)(void) {
	NIM_CHAR result;
	int fd;
	struct termios oldMode;
	int T1_;
	int T2_;
	nimfr_("getch", "terminal.nim");
	result = (NIM_CHAR)0;
	nimln_(732, "terminal.nim");
	fd = getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg(stdin);
	memset((void*)(&oldMode), 0, sizeof(oldMode));
	nimln_(734, "terminal.nim");
	T1_ = (int)0;
	T1_ = tcgetattr(fd, (&oldMode));
	T1_;
	nimln_(735, "terminal.nim");
	setRaw_bWuPmHcnrBG1QQlDC4s7ug(fd, TCSAFLUSH);
	nimln_(736, "terminal.nim");
	result = readChar_ufPUIQ2Rg4xhWjWigciDOg(stdin);
	nimln_(737, "terminal.nim");
	T2_ = (int)0;
	T2_ = tcsetattr(fd, TCSADRAIN, (&oldMode));
	T2_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readPasswordFromStdin_HR8zZ5lRzcgpZhC3TYXnoQ)(NimStringDesc* prompt, NimStringDesc** password) {
	NIM_BOOL result;
	int fd;
	struct termios cur;
	struct termios old;
	int T1_;
	int T2_;
	int T3_;
	nimfr_("readPasswordFromStdin", "terminal.nim");
	result = (NIM_BOOL)0;
	nimln_(771, "terminal.nim");
	(*password) = setLengthStr((*password), ((NI) 0));
	nimln_(772, "terminal.nim");
	fd = getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg(stdin);
	memset((void*)(&cur), 0, sizeof(cur));
	memset((void*)(&old), 0, sizeof(old));
	nimln_(774, "terminal.nim");
	T1_ = (int)0;
	T1_ = tcgetattr(fd, (&cur));
	T1_;
	nimln_(775, "terminal.nim");
	old = cur;
	nimln_(776, "terminal.nim");
	cur.c_lflag = (NU32)(cur.c_lflag & (NU32)((NU32) ~(ECHO)));
	nimln_(777, "terminal.nim");
	T2_ = (int)0;
	T2_ = tcsetattr(fd, TCSADRAIN, (&cur));
	T2_;
	nimln_(778, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(stdout, prompt);
	nimln_(779, "terminal.nim");
	result = readLine_sO1bQXVRA6RP9cdYJXNKeSw(stdin, password);
	nimln_(780, "terminal.nim");
	write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_26));
	nimln_(781, "terminal.nim");
	T3_ = (int)0;
	T3_ = tcsetattr(fd, TCSADRAIN, (&old));
	T3_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readPasswordFromStdin_ucTCJi9arxLW5NPhud9bqzAA)(NimStringDesc* prompt) {
	NimStringDesc* result;
	NIM_BOOL T1_;
	nimfr_("readPasswordFromStdin", "terminal.nim");
	result = (NimStringDesc*)0;
	nimln_(785, "terminal.nim");
	result = copyString(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_6));
	nimln_(786, "terminal.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = readPasswordFromStdin_HR8zZ5lRzcgpZhC3TYXnoQ(prompt, (&result));
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void) {
	nimfr_("resetAttributes", "terminal.nim");
	nimln_(816, "terminal.nim");
	resetAttributes_tFIu39aFSR3N0M64Ynwugng_5(stdout);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isTrueColorSupported_pgygBZbo45KrYv6AmVkHkQ)(void) {
	NIM_BOOL result;
	nimfr_("isTrueColorSupported", "terminal.nim");
{	result = (NIM_BOOL)0;
	nimln_(830, "terminal.nim");
	result = trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQasyncdispatch)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_CN3raB9atujkEiPpxYAdlgQ_27;
				NI TM_CN3raB9atujkEiPpxYAdlgQ_28;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_27 = addInt(result, ((NI) 1));
				result = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_27);
				nimln_(2188, "system.nim");
				TM_CN3raB9atujkEiPpxYAdlgQ_28 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_28);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwasyncdispatch)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQasyncdispatch(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, enableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w)(void) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("enableTrueColors", "terminal.nim");
	nimln_(863, "terminal.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_32), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_6));
	T2_ = (NimStringDesc*)0;
	T2_ = nsuToLowerAsciiStr(T1_);
	trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw = contains_jPdUhZfr9a8sH2V3ZBDljzwasyncdispatch(TM_CN3raB9atujkEiPpxYAdlgQ_29, 2, T2_);
	nimln_(864, "terminal.nim");
	trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ = trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, disableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w_2)(void) {
	nimfr_("disableTrueColors", "terminal.nim");
	nimln_(877, "terminal.nim");
	trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ = NIM_FALSE;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void) {
	nimfr_("terminal", "terminal.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void) {
}

