/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /root/remedias/nim/nimcache/stdlib_db_common.o /root/remedias/nim/nimcache/stdlib_db_common.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_DbError_w65gHFDlremRAyGJ4f6zkA tyObject_DbError_w65gHFDlremRAyGJ4f6zkA;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_DbError_w65gHFDlremRAyGJ4f6zkA {
  tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray_xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
NI gcThreadId;
};
typedef NU8 tyEnum_DbTypeKind_hWTAT1Bbab0m1uhTtrCGTA;
struct tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag {
tyEnum_DbTypeKind_hWTAT1Bbab0m1uhTtrCGTA kind;
NIM_BOOL notNull;
NimStringDesc* name;
NI size;
NI maxReprLen;
NI precision;
NI scale;
NI64 min;
NI64 max;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* validValues;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOINLINE(void, dbError_tQVzz9a0fa0An0UxEixDvaA)(NimStringDesc* msg) __attribute__((noreturn));
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_HDK9arR7eW5QkLI9bRSdsGnA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
TNimType NTI_w65gHFDlremRAyGJ4f6zkA_;
TNimType NTI_HDK9arR7eW5QkLI9bRSdsGnA_;
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_J9aQt1VUI9awa3F8C7cw2G9ag_;
TNimType NTI_hWTAT1Bbab0m1uhTtrCGTA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_hLlQjbV9bLNq5PFxYcqacsA_;
extern TNimType NTI_Aav8dQoMlCFnZRxA0IhTHQ_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
static N_NIMCALL(void, Marker_tyRef_HDK9arR7eW5QkLI9bRSdsGnA)(void* p, NI op) {
	tyObject_DbError_w65gHFDlremRAyGJ4f6zkA* a;
	a = (tyObject_DbError_w65gHFDlremRAyGJ4f6zkA*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NOINLINE(void, dbError_tQVzz9a0fa0An0UxEixDvaA)(NimStringDesc* msg) {
	tyObject_DbError_w65gHFDlremRAyGJ4f6zkA* e;
	NimStringDesc* T1_;
	nimfr_("dbError", "db_common.nim");
	e = (tyObject_DbError_w65gHFDlremRAyGJ4f6zkA*)0;
	nimln_(101, "db_common.nim");
	e = (tyObject_DbError_w65gHFDlremRAyGJ4f6zkA*) newObj((&NTI_HDK9arR7eW5QkLI9bRSdsGnA_), sizeof(tyObject_DbError_w65gHFDlremRAyGJ4f6zkA));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI_w65gHFDlremRAyGJ4f6zkA_);
	nimln_(102, "db_common.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.Sup.Sup.message; (*e).Sup.Sup.Sup.message = copyStringRC1(msg);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(103, "db_common.nim");
	raiseException((Exception*)e, "DbError");
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_db_commonInit000)(void) {
	nimfr_("db_common", "db_common.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_db_commonDatInit000)(void) {
static TNimNode* TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[10];
static TNimNode* TM_roPg9aXsZrBZMcw9a0dVfzaQ_3[40];
NI TM_roPg9aXsZrBZMcw9a0dVfzaQ_5;
static char* NIM_CONST TM_roPg9aXsZrBZMcw9a0dVfzaQ_4[40] = {
"dbUnknown", 
"dbSerial", 
"dbNull", 
"dbBit", 
"dbBool", 
"dbBlob", 
"dbFixedChar", 
"dbVarchar", 
"dbJson", 
"dbXml", 
"dbInt", 
"dbUInt", 
"dbDecimal", 
"dbFloat", 
"dbDate", 
"dbTime", 
"dbDatetime", 
"dbTimestamp", 
"dbTimeInterval", 
"dbEnum", 
"dbSet", 
"dbArray", 
"dbComposite", 
"dbUrl", 
"dbUuid", 
"dbInet", 
"dbMacAddress", 
"dbGeometry", 
"dbPoint", 
"dbLine", 
"dbLseg", 
"dbBox", 
"dbPath", 
"dbPolygon", 
"dbCircle", 
"dbUser1", 
"dbUser2", 
"dbUser3", 
"dbUser4", 
"dbUser5"};
static TNimNode TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[53];
NTI_w65gHFDlremRAyGJ4f6zkA_.size = sizeof(tyObject_DbError_w65gHFDlremRAyGJ4f6zkA);
NTI_w65gHFDlremRAyGJ4f6zkA_.kind = 17;
NTI_w65gHFDlremRAyGJ4f6zkA_.base = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[0].len = 0; TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[0].kind = 2;
NTI_w65gHFDlremRAyGJ4f6zkA_.node = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[0];
NTI_HDK9arR7eW5QkLI9bRSdsGnA_.size = sizeof(tyObject_DbError_w65gHFDlremRAyGJ4f6zkA*);
NTI_HDK9arR7eW5QkLI9bRSdsGnA_.kind = 22;
NTI_HDK9arR7eW5QkLI9bRSdsGnA_.base = (&NTI_w65gHFDlremRAyGJ4f6zkA_);
NTI_HDK9arR7eW5QkLI9bRSdsGnA_.marker = Marker_tyRef_HDK9arR7eW5QkLI9bRSdsGnA;
NTI_J9aQt1VUI9awa3F8C7cw2G9ag_.size = sizeof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag);
NTI_J9aQt1VUI9awa3F8C7cw2G9ag_.kind = 18;
NTI_J9aQt1VUI9awa3F8C7cw2G9ag_.base = 0;
NTI_J9aQt1VUI9awa3F8C7cw2G9ag_.flags = 2;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[0] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[2];
NTI_hWTAT1Bbab0m1uhTtrCGTA_.size = sizeof(tyEnum_DbTypeKind_hWTAT1Bbab0m1uhTtrCGTA);
NTI_hWTAT1Bbab0m1uhTtrCGTA_.kind = 14;
NTI_hWTAT1Bbab0m1uhTtrCGTA_.base = 0;
NTI_hWTAT1Bbab0m1uhTtrCGTA_.flags = 3;
for (TM_roPg9aXsZrBZMcw9a0dVfzaQ_5 = 0; TM_roPg9aXsZrBZMcw9a0dVfzaQ_5 < 40; TM_roPg9aXsZrBZMcw9a0dVfzaQ_5++) {
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[TM_roPg9aXsZrBZMcw9a0dVfzaQ_5+3].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[TM_roPg9aXsZrBZMcw9a0dVfzaQ_5+3].offset = TM_roPg9aXsZrBZMcw9a0dVfzaQ_5;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[TM_roPg9aXsZrBZMcw9a0dVfzaQ_5+3].name = TM_roPg9aXsZrBZMcw9a0dVfzaQ_4[TM_roPg9aXsZrBZMcw9a0dVfzaQ_5];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_3[TM_roPg9aXsZrBZMcw9a0dVfzaQ_5] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[TM_roPg9aXsZrBZMcw9a0dVfzaQ_5+3];
}
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[43].len = 40; TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[43].kind = 2; TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[43].sons = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_3[0];
NTI_hWTAT1Bbab0m1uhTtrCGTA_.node = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[43];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[2].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[2].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, kind);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[2].typ = (&NTI_hWTAT1Bbab0m1uhTtrCGTA_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[2].name = "kind";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[1] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[44];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[44].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[44].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, notNull);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[44].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[44].name = "notNull";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[2] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[45];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[45].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[45].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, name);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[45].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[45].name = "name";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[3] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[46];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[46].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[46].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, size);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[46].typ = (&NTI_hLlQjbV9bLNq5PFxYcqacsA_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[46].name = "size";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[4] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[47];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[47].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[47].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, maxReprLen);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[47].typ = (&NTI_hLlQjbV9bLNq5PFxYcqacsA_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[47].name = "maxReprLen";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[5] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[48];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[48].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[48].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, precision);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[48].typ = (&NTI_hLlQjbV9bLNq5PFxYcqacsA_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[48].name = "precision";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[6] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[49];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[49].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[49].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, scale);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[49].typ = (&NTI_hLlQjbV9bLNq5PFxYcqacsA_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[49].name = "scale";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[7] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[50];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[50].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[50].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, min);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[50].typ = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[50].name = "min";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[8] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[51];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[51].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[51].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, max);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[51].typ = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[51].name = "max";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[9] = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[52];
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[52].kind = 1;
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[52].offset = offsetof(tyObject_DbType_J9aQt1VUI9awa3F8C7cw2G9ag, validValues);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[52].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[52].name = "validValues";
TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[1].len = 10; TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[1].kind = 2; TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[1].sons = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_2[0];
NTI_J9aQt1VUI9awa3F8C7cw2G9ag_.node = &TM_roPg9aXsZrBZMcw9a0dVfzaQ_0[1];
}

