/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /root/remedias/nim/nimcache/stdlib_postgres.o /root/remedias/nim/nimcache/stdlib_postgres.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA;
typedef struct tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw;
typedef struct tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PGresAttDesc_KPdhVeVCFvGF79bxTyvEM8g tyObject_PGresAttDesc_KPdhVeVCFvGF79bxTyvEM8g;
typedef struct tyObject_PGresAttValue_iEhoe1M5fOiznRdV9bHTazg tyObject_PGresAttValue_iEhoe1M5fOiznRdV9bHTazg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NCSTRING, tyProc_aQjVyXyE9bVC58dNHJADoKg) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn);
typedef N_CDECL_PTR(tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw*, tyProc_bx6zpQZ9bbD8WlXZaBVvF0g) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn, NCSTRING command, NI32 nParams, NI32* paramTypes, NCSTRING* paramValues, NI32* paramLengths, NI32* paramFormats, NI32 resultFormat);
typedef NU8 tyEnum_ExecStatusType_adWskXOLirFTlnA2JHWZGg;
typedef N_CDECL_PTR(tyEnum_ExecStatusType_adWskXOLirFTlnA2JHWZGg, tyProc_gNItmrVJZy6VcZ5MF8bScA) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res);
typedef N_CDECL_PTR(void, tyProc_nrdssKDeyie9aYTbHtRjJow) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res);
typedef N_CDECL_PTR(tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw*, tyProc_C9bChr9bJIbuHgqYIv9cY1pzA) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn, NCSTRING stmtName, NI32 nParams, NCSTRING* paramValues, NI32* paramLengths, NI32* paramFormats, NI32 resultFormat);
typedef N_CDECL_PTR(tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw*, tyProc_Gq8tNXNmoKUZAMwwq8S8Qw) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn, NCSTRING query);
typedef N_CDECL_PTR(tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw*, tyProc_OV9b9cruOYW7ZAQkOiIlRlUQ) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn, NCSTRING stmtName, NCSTRING query, NI32 nParams, NI32* paramTypes);
typedef N_CDECL_PTR(NCSTRING, tyProc_Xq6N0E2zGEqPbBbmBS3MlA) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res, NI32 tup_num, NI32 field_num);
typedef N_CDECL_PTR(NI32, tyProc_kSWSmWCw3wMRbxJZynw3GQ) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res, NI32 field_num);
typedef N_CDECL_PTR(NCSTRING, tyProc_xsKoEm9cmNAe9cs0S0pY3B4A) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res, NI32 field_num);
typedef N_CDECL_PTR(NI32, tyProc_gQwlaJTKpTG9arqEe0CcHyg) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res);
typedef N_CDECL_PTR(NCSTRING, tyProc_cm8aCfz9bltVhRrMCcmFcWQ) (tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw* res);
typedef N_CDECL_PTR(void, tyProc_mRMmUY4AvEr9aSAyQm9aWxMA) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn);
typedef N_CDECL_PTR(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA*, tyProc_Rpw3jzfFz39bnGztYItYmqA) (NCSTRING pghost, NCSTRING pgport, NCSTRING pgoptions, NCSTRING pgtty, NCSTRING dbName, NCSTRING login, NCSTRING pwd);
typedef NU8 tyEnum_ConnStatusType_Zk09bslxvUz82U9atXAtjT9bw;
typedef N_CDECL_PTR(tyEnum_ConnStatusType_Zk09bslxvUz82U9atXAtjT9bw, tyProc_NdooOid9adcjcRxzX7l2Ahg) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn);
typedef N_CDECL_PTR(NI32, tyProc_MO1w9b2NkFMfv8siHhxTlAg) (tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn, NCSTRING encoding);
typedef NIM_CHAR tyArray_YgmC9cqmvoS8mTDWNFPoxpQ[4096];
typedef NI8 tyArray_xQuItyNBcDleN9c88oPSSRg[112];
typedef NIM_CHAR tyArray_1N75LKnZklmK4NsXtZ9bZiA[2];
struct tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA {
NCSTRING pghost;
NCSTRING pgtty;
NCSTRING pgport;
NCSTRING pgoptions;
NCSTRING dbName;
tyEnum_ConnStatusType_Zk09bslxvUz82U9atXAtjT9bw status;
tyArray_YgmC9cqmvoS8mTDWNFPoxpQ errorMessage;
FILE* Pfin;
FILE* Pfout;
FILE* Pfdebug;
NI32 sock;
tyArray_xQuItyNBcDleN9c88oPSSRg laddr;
tyArray_xQuItyNBcDleN9c88oPSSRg raddr;
tyArray_1N75LKnZklmK4NsXtZ9bZiA salt;
NI32 asyncNotifyWaiting;
void* notifyList;
NCSTRING pguser;
NCSTRING pgpass;
tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag* lobjfuncs;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag {
NI32 fn_lo_open;
NI32 fn_lo_close;
NI32 fn_lo_creat;
NI32 fn_lo_unlink;
NI32 fn_lo_lseek;
NI32 fn_lo_tell;
NI32 fn_lo_read;
NI32 fn_lo_write;
};
typedef NIM_CHAR tyArray_qzJ2N5BE6ztjKybArqQGmg[40];
struct tyObject_PGresult_MOVdJjbhYqU36sihIXfrMw {
NI32 ntups;
NI32 numAttributes;
tyObject_PGresAttDesc_KPdhVeVCFvGF79bxTyvEM8g* attDescs;
tyObject_PGresAttValue_iEhoe1M5fOiznRdV9bHTazg** tuples;
NI32 tupArrSize;
tyEnum_ExecStatusType_adWskXOLirFTlnA2JHWZGg resultStatus;
tyArray_qzJ2N5BE6ztjKybArqQGmg cmdStatus;
NI32 binary;
tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA* conn;
};
struct tyObject_PGresAttDesc_KPdhVeVCFvGF79bxTyvEM8g {
NCSTRING name;
NI32 adtid;
NI adtsize;
};
struct tyObject_PGresAttValue_iEhoe1M5fOiznRdV9bHTazg {
NI32 length;
NCSTRING value;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2;
tyProc_aQjVyXyE9bVC58dNHJADoKg Dl_269511_;
tyProc_bx6zpQZ9bbD8WlXZaBVvF0g Dl_269626_;
tyProc_gNItmrVJZy6VcZ5MF8bScA Dl_269747_;
tyProc_nrdssKDeyie9aYTbHtRjJow Dl_269828_;
tyProc_C9bChr9bJIbuHgqYIv9cY1pzA Dl_269644_;
tyProc_Gq8tNXNmoKUZAMwwq8S8Qw Dl_269622_;
tyProc_OV9b9cruOYW7ZAQkOiIlRlUQ Dl_269637_;
tyProc_Xq6N0E2zGEqPbBbmBS3MlA Dl_269813_;
tyProc_kSWSmWCw3wMRbxJZynw3GQ Dl_269789_;
tyProc_xsKoEm9cmNAe9cs0S0pY3B4A Dl_269769_;
tyProc_kSWSmWCw3wMRbxJZynw3GQ Dl_269777_;
tyProc_gQwlaJTKpTG9arqEe0CcHyg Dl_269763_;
tyProc_gQwlaJTKpTG9arqEe0CcHyg Dl_269760_;
tyProc_cm8aCfz9bltVhRrMCcmFcWQ Dl_269810_;
tyProc_mRMmUY4AvEr9aSAyQm9aWxMA Dl_269457_;
tyProc_Rpw3jzfFz39bnGztYItYmqA Dl_269441_;
tyProc_NdooOid9adcjcRxzX7l2Ahg Dl_269498_;
tyProc_MO1w9b2NkFMfv8siHhxTlAg Dl_269523_;
TNimType NTI_BabfURiiS9a6eeOUNAso2xA_;
extern TNimType NTI_S9agCYBinaYZnGWcjTdxclg_;
TNimType NTI_Zk09bslxvUz82U9atXAtjT9bw_;
extern TNimType NTI_nmiMWKVIe46vacnhAFrQvw_;
TNimType NTI_YgmC9cqmvoS8mTDWNFPoxpQ_;
extern TNimType NTI_7BHnQsEj49a9c6QtudqWTo1w_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_chXunH2dwinSkhpA6JnsXw_;
TNimType NTI_xQuItyNBcDleN9c88oPSSRg_;
TNimType NTI_1N75LKnZklmK4NsXtZ9bZiA_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI_xUnU9byS9bZT3IK6U7CdpQag_;
TNimType NTI_yHgiR7lwsBTc8H4NpwzhHQ_;
TNimType NTI_V2UtEhsZQpGx8S0HzSg9c0Q_;
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_4, "libpq.so.5", 10);
STRING_LITERAL(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_6, "libpq.so", 8);
STRING_LITERAL(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_7, "libpq.so(.5|)", 13);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_postgresInit000)(void) {
	nimfr_("postgres", "postgres.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_postgresDatInit000)(void) {
static TNimNode* TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[19];
static TNimNode* TM_p9aV4GCFSjVcgl5WCT9cbt4Q_45[9];
NI TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47;
static char* NIM_CONST TM_p9aV4GCFSjVcgl5WCT9cbt4Q_46[9] = {
"CONNECTION_OK", 
"CONNECTION_BAD", 
"CONNECTION_STARTED", 
"CONNECTION_MADE", 
"CONNECTION_AWAITING_RESPONSE", 
"CONNECTION_AUTH_OK", 
"CONNECTION_SETENV", 
"CONNECTION_SSL_STARTUP", 
"CONNECTION_NEEDED"};
static TNimNode* TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[8];
static TNimNode TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[39];
NTI_BabfURiiS9a6eeOUNAso2xA_.size = sizeof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA);
NTI_BabfURiiS9a6eeOUNAso2xA_.kind = 18;
NTI_BabfURiiS9a6eeOUNAso2xA_.base = 0;
NTI_BabfURiiS9a6eeOUNAso2xA_.flags = 3;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[0] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[1];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[1].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[1].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, pghost);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[1].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[1].name = "pghost";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[1] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[2];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[2].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[2].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, pgtty);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[2].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[2].name = "pgtty";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[2] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[3];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[3].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[3].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, pgport);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[3].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[3].name = "pgport";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[3] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[4];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[4].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[4].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, pgoptions);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[4].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[4].name = "pgoptions";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[4] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[5];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[5].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[5].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, dbName);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[5].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[5].name = "dbName";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[5] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[6];
NTI_Zk09bslxvUz82U9atXAtjT9bw_.size = sizeof(tyEnum_ConnStatusType_Zk09bslxvUz82U9atXAtjT9bw);
NTI_Zk09bslxvUz82U9atXAtjT9bw_.kind = 14;
NTI_Zk09bslxvUz82U9atXAtjT9bw_.base = 0;
NTI_Zk09bslxvUz82U9atXAtjT9bw_.flags = 3;
for (TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47 = 0; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47 < 9; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47++) {
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47+7].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47+7].offset = TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47+7].name = TM_p9aV4GCFSjVcgl5WCT9cbt4Q_46[TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_45[TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[TM_p9aV4GCFSjVcgl5WCT9cbt4Q_47+7];
}
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[16].len = 9; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[16].kind = 2; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[16].sons = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_45[0];
NTI_Zk09bslxvUz82U9atXAtjT9bw_.node = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[16];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[6].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[6].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, status);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[6].typ = (&NTI_Zk09bslxvUz82U9atXAtjT9bw_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[6].name = "status";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[6] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[17];
NTI_YgmC9cqmvoS8mTDWNFPoxpQ_.size = sizeof(tyArray_YgmC9cqmvoS8mTDWNFPoxpQ);
NTI_YgmC9cqmvoS8mTDWNFPoxpQ_.kind = 16;
NTI_YgmC9cqmvoS8mTDWNFPoxpQ_.base = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
NTI_YgmC9cqmvoS8mTDWNFPoxpQ_.flags = 3;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[17].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[17].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, errorMessage);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[17].typ = (&NTI_YgmC9cqmvoS8mTDWNFPoxpQ_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[17].name = "errorMessage";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[7] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[18];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[18].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[18].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, Pfin);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[18].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[18].name = "Pfin";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[8] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[19];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[19].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[19].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, Pfout);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[19].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[19].name = "Pfout";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[9] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[20];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[20].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[20].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, Pfdebug);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[20].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[20].name = "Pfdebug";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[10] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[21];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[21].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[21].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, sock);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[21].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[21].name = "sock";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[11] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[22];
NTI_xQuItyNBcDleN9c88oPSSRg_.size = sizeof(tyArray_xQuItyNBcDleN9c88oPSSRg);
NTI_xQuItyNBcDleN9c88oPSSRg_.kind = 16;
NTI_xQuItyNBcDleN9c88oPSSRg_.base = (&NTI_chXunH2dwinSkhpA6JnsXw_);
NTI_xQuItyNBcDleN9c88oPSSRg_.flags = 3;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[22].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[22].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, laddr);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[22].typ = (&NTI_xQuItyNBcDleN9c88oPSSRg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[22].name = "laddr";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[12] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[23];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[23].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[23].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, raddr);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[23].typ = (&NTI_xQuItyNBcDleN9c88oPSSRg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[23].name = "raddr";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[13] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[24];
NTI_1N75LKnZklmK4NsXtZ9bZiA_.size = sizeof(tyArray_1N75LKnZklmK4NsXtZ9bZiA);
NTI_1N75LKnZklmK4NsXtZ9bZiA_.kind = 16;
NTI_1N75LKnZklmK4NsXtZ9bZiA_.base = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
NTI_1N75LKnZklmK4NsXtZ9bZiA_.flags = 3;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[24].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[24].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, salt);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[24].typ = (&NTI_1N75LKnZklmK4NsXtZ9bZiA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[24].name = "salt";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[14] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[25];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[25].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[25].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, asyncNotifyWaiting);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[25].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[25].name = "asyncNotifyWaiting";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[15] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[26];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[26].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[26].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, notifyList);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[26].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[26].name = "notifyList";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[16] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[27];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[27].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[27].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, pguser);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[27].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[27].name = "pguser";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[17] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[28];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[28].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[28].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, pgpass);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[28].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[28].name = "pgpass";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[18] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[29];
NTI_xUnU9byS9bZT3IK6U7CdpQag_.size = sizeof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag);
NTI_xUnU9byS9bZT3IK6U7CdpQag_.kind = 18;
NTI_xUnU9byS9bZT3IK6U7CdpQag_.base = 0;
NTI_xUnU9byS9bZT3IK6U7CdpQag_.flags = 3;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[0] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[31];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[31].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[31].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_open);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[31].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[31].name = "fn_lo_open";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[1] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[32];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[32].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[32].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_close);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[32].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[32].name = "fn_lo_close";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[2] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[33];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[33].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[33].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_creat);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[33].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[33].name = "fn_lo_creat";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[3] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[34];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[34].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[34].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_unlink);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[34].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[34].name = "fn_lo_unlink";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[4] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[35];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[35].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[35].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_lseek);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[35].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[35].name = "fn_lo_lseek";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[5] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[36];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[36].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[36].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_tell);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[36].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[36].name = "fn_lo_tell";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[6] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[37];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[37].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[37].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_read);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[37].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[37].name = "fn_lo_read";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[7] = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[38];
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[38].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[38].offset = offsetof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag, fn_lo_write);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[38].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[38].name = "fn_lo_write";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[30].len = 8; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[30].kind = 2; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[30].sons = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_48[0];
NTI_xUnU9byS9bZT3IK6U7CdpQag_.node = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[30];
NTI_yHgiR7lwsBTc8H4NpwzhHQ_.size = sizeof(tyObject_PGlobjfuncs_xUnU9byS9bZT3IK6U7CdpQag*);
NTI_yHgiR7lwsBTc8H4NpwzhHQ_.kind = 21;
NTI_yHgiR7lwsBTc8H4NpwzhHQ_.base = (&NTI_xUnU9byS9bZT3IK6U7CdpQag_);
NTI_yHgiR7lwsBTc8H4NpwzhHQ_.flags = 3;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[29].kind = 1;
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[29].offset = offsetof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA, lobjfuncs);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[29].typ = (&NTI_yHgiR7lwsBTc8H4NpwzhHQ_);
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[29].name = "lobjfuncs";
TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[0].len = 19; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[0].kind = 2; TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[0].sons = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_44[0];
NTI_BabfURiiS9a6eeOUNAso2xA_.node = &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_0[0];
NTI_V2UtEhsZQpGx8S0HzSg9c0Q_.size = sizeof(tyObject_PGconn_BabfURiiS9a6eeOUNAso2xA*);
NTI_V2UtEhsZQpGx8S0HzSg9c0Q_.kind = 21;
NTI_V2UtEhsZQpGx8S0HzSg9c0Q_.base = (&NTI_BabfURiiS9a6eeOUNAso2xA_);
NTI_V2UtEhsZQpGx8S0HzSg9c0Q_.flags = 3;
if (!((TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2 = nimLoadLibrary((NimStringDesc*) &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_4))
||(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2 = nimLoadLibrary((NimStringDesc*) &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_6))
)) nimLoadLibraryError((NimStringDesc*) &TM_p9aV4GCFSjVcgl5WCT9cbt4Q_7);
	Dl_269511_ = (tyProc_aQjVyXyE9bVC58dNHJADoKg) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQerrorMessage");
	Dl_269626_ = (tyProc_bx6zpQZ9bbD8WlXZaBVvF0g) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQexecParams");
	Dl_269747_ = (tyProc_gNItmrVJZy6VcZ5MF8bScA) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQresultStatus");
	Dl_269828_ = (tyProc_nrdssKDeyie9aYTbHtRjJow) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQclear");
	Dl_269644_ = (tyProc_C9bChr9bJIbuHgqYIv9cY1pzA) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQexecPrepared");
	Dl_269622_ = (tyProc_Gq8tNXNmoKUZAMwwq8S8Qw) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQexec");
	Dl_269637_ = (tyProc_OV9b9cruOYW7ZAQkOiIlRlUQ) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQprepare");
	Dl_269813_ = (tyProc_Xq6N0E2zGEqPbBbmBS3MlA) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQgetvalue");
	Dl_269789_ = (tyProc_kSWSmWCw3wMRbxJZynw3GQ) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQftype");
	Dl_269769_ = (tyProc_xsKoEm9cmNAe9cs0S0pY3B4A) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQfname");
	Dl_269777_ = (tyProc_kSWSmWCw3wMRbxJZynw3GQ) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQftable");
	Dl_269763_ = (tyProc_gQwlaJTKpTG9arqEe0CcHyg) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQnfields");
	Dl_269760_ = (tyProc_gQwlaJTKpTG9arqEe0CcHyg) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQntuples");
	Dl_269810_ = (tyProc_cm8aCfz9bltVhRrMCcmFcWQ) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQcmdTuples");
	Dl_269457_ = (tyProc_mRMmUY4AvEr9aSAyQm9aWxMA) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQfinish");
	Dl_269441_ = (tyProc_Rpw3jzfFz39bnGztYItYmqA) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQsetdbLogin");
	Dl_269498_ = (tyProc_NdooOid9adcjcRxzX7l2Ahg) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQstatus");
	Dl_269523_ = (tyProc_MO1w9b2NkFMfv8siHhxTlAg) nimGetProcAddr(TM_p9aV4GCFSjVcgl5WCT9cbt4Q_2, "PQsetClientEncoding");
}

