/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /root/remedias/nim/nimcache/stdlib_cpuload.o /root/remedias/nim/nimcache/stdlib_cpuload.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA {
NI calls;
};
N_LIB_PRIVATE N_NIMCALL(tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open_sEp0GH2306oGo9bqBpj5oTQ)(FILE** f, NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NI, ncpicountProcessors)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_CFWzmO8DEHxStvjr8GyqGg_2, "/proc/loadavg", 13);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA* s) {
	tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig result;
	FILE* f;
	NI TM_CFWzmO8DEHxStvjr8GyqGg_6;
	nimfr_("advice", "cpuload.nim");
	result = (tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;
	f = (FILE*)0;
	nimln_(64, "cpuload.nim");
	{
		NIM_BOOL T3_;
		NF b;
		NI busy;
		NI total;
		NI cpus;
		T3_ = (NIM_BOOL)0;
		T3_ = open_sEp0GH2306oGo9bqBpj5oTQ(&f, ((NimStringDesc*) &TM_CFWzmO8DEHxStvjr8GyqGg_2), ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
		if (!T3_) goto LA4_;
		b = (NF)0;
		busy = (NI)0;
		total = (NI)0;
		nimln_(67, "cpuload.nim");
		fscanf(f, "%lf %lf %lf %ld/%ld", (&b), (&b), (&b), (&busy), (&total));
		nimln_(69, "cpuload.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
		nimln_(70, "cpuload.nim");
		cpus = ncpicountProcessors();
		nimln_(71, "cpuload.nim");
		{
			NI TM_CFWzmO8DEHxStvjr8GyqGg_3;
			TM_CFWzmO8DEHxStvjr8GyqGg_3 = subInt(busy, ((NI) 1));
			if (!((NI)(TM_CFWzmO8DEHxStvjr8GyqGg_3) < cpus)) goto LA8_;
			nimln_(72, "cpuload.nim");
			result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1);
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM_CFWzmO8DEHxStvjr8GyqGg_4;
			NI TM_CFWzmO8DEHxStvjr8GyqGg_5;
			nimln_(73, "cpuload.nim");
			TM_CFWzmO8DEHxStvjr8GyqGg_4 = mulInt(cpus, ((NI) 2));
			TM_CFWzmO8DEHxStvjr8GyqGg_5 = subInt(busy, ((NI) 1));
			if (!((NI)(TM_CFWzmO8DEHxStvjr8GyqGg_4) <= (NI)(TM_CFWzmO8DEHxStvjr8GyqGg_5))) goto LA11_;
			nimln_(74, "cpuload.nim");
			result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2);
		}
		goto LA6_;
		LA11_: ;
		{
			nimln_(76, "cpuload.nim");
			result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0);
		}
		LA6_: ;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(78, "cpuload.nim");
		result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0);
	}
	LA1_: ;
	nimln_(82, "cpuload.nim");
	TM_CFWzmO8DEHxStvjr8GyqGg_6 = addInt((*s).calls, ((NI) 1));
	(*s).calls = (NI)(TM_CFWzmO8DEHxStvjr8GyqGg_6);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void) {
	nimfr_("cpuload", "cpuload.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void) {
}

