/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /root/remedias/nim/nimcache/watchman_cli.o /root/remedias/nim/nimcache/watchman_cli.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA;
typedef struct tyObject_HashSet_OWHFqZn3R9csWXH86N7Rq2g tyObject_HashSet_OWHFqZn3R9csWXH86N7Rq2g;
typedef struct tySequence_9aUBm188mcn7WjIGymvBT5w tySequence_9aUBm188mcn7WjIGymvBT5w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_IO6xTHa6y0i7uNmStF6URw tyTuple_IO6xTHa6y0i7uNmStF6URw;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg tyArray_GiYrhMLnoPdkfRTUU6LIhQ[4];
typedef NU8 tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA;
typedef tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA tyArray_oMqFgyNoOZJl4DxunxAFUQ[4];
typedef NU8 tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig;
struct tyObject_HashSet_OWHFqZn3R9csWXH86N7Rq2g {
tySequence_9aUBm188mcn7WjIGymvBT5w* data;
NI counter;
};
struct tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA {
tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig level;
tyObject_HashSet_OWHFqZn3R9csWXH86N7Rq2g warnings;
NI suppressionCount;
NIM_BOOL showColor;
NIM_BOOL suppressMessages;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray_xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
NI gcThreadId;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw;
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ;
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyTuple_IO6xTHa6y0i7uNmStF6URw {
NI Field0;
tyTuple_UV3llMMYFckfui8YMBuUZA Field1;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_9aUBm188mcn7WjIGymvBT5w {
  TGenericSeq Sup;
  tyTuple_IO6xTHa6y0i7uNmStF6URw data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*, newCLI_7309acyOAhDSDzw9ba88Ia1A)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_ybQzX9cMrXjEj9bNZNlkjOKg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_NIMCALL(void, TM_JOguTJkl9cZuE2nrrLMMejw_6)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, maybe_init_cli_Lw25hsj6cTkdNxUweulhgQ)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NI, calculateCategoryOffset_vhBplFmZ5l09cMTyuMBWUAQ)(NimStringDesc* category);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, displayCategory_8gabfQYbrSJGf6bhbE9a2ug)(NimStringDesc* category, tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw displayType, tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig priority);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright);
N_LIB_PRIVATE N_NIMCALL(void, writeStyled_jPzCz3P0CaIFIvdlX9aQd4w)(NimStringDesc* txt, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style);
N_LIB_PRIVATE N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, displayLine_F5zrZ9ax9bfLmb45G31Ablqw)(NimStringDesc* category, NimStringDesc* line, tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw displayType, tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig priority);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, display_elIA49aZ9bc7gVVNzTpH3rtw)(NimStringDesc* category, NimStringDesc* msg, tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw displayType, tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig priority);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(void, displayDebug_IV2tE9cOAkZZXLKBePZUCQg)(NimStringDesc* category, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, displayDebug_ZniuJ2GtraBfb5W0ruIkVw)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, displayTip_Lw25hsj6cTkdNxUweulhgQ_2)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, prompt_rEJhBlhpUUtRqzlsDY1k6g)(tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ forcePrompts, NimStringDesc* question);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuNormalize)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, promptCustom_NZBEV3Zh0VsRxKiive9aWgQ)(tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ forcePrompts, NimStringDesc* question, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, promptCustom_zFHrbyrtNEPjp9ba7Hi6rZw)(NimStringDesc* question, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, promptList_5gAXhc5LjOBogWUPyn3jWA)(tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ forcePrompts, NimStringDesc* question, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(void, setVerbosity_Oyc7NfoFVBC8BaTDuMeUeg)(tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig level);
N_LIB_PRIVATE N_NIMCALL(void, setShowColor_xZJghI4p8WoXA4wzL6Z9bng)(NIM_BOOL val);
N_LIB_PRIVATE N_NIMCALL(void, setSuppressMessages_xZJghI4p8WoXA4wzL6Z9bng_2)(NIM_BOOL val);
TNimType NTI_jDewjhp9a60tOuoQbdqvxBA_;
TNimType NTI_4B6X6c5gq8OV1pR0JsF1ig_;
extern TNimType NTI_OWHFqZn3R9csWXH86N7Rq2g_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_ybQzX9cMrXjEj9bNZNlkjOKg_;
extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_THREADVAR tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA* threadCLI_zu7MhEebleCIn6IYLlEuQg;
extern NIM_THREADVAR tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_CONST tyArray_GiYrhMLnoPdkfRTUU6LIhQ foregrounds_oX2Nv5KNcGkglUgeHYluAQ = {((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 31),
((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 33),
((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 36),
((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 32)}
;
NIM_CONST tyArray_oMqFgyNoOZJl4DxunxAFUQ styles_1JthzQ2h4VcH4b9cqyYEYPw = {2,
2,
0,
1}
;
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_7, "len(category) <= 11 ", 20);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_9, "$1$2 ", 5);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_10, "\012", 1);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_14, "...", 3);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_19, "Debug:", 6);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_20, "$1 messages have been suppressed, use --verbose to show them.", 61);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_21, "Tip:", 4);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_22, "Prompt:", 7);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_23, " -> [forced yes]", 16);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_24, " -> [forced no]", 15);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_25, " [y/N]", 6);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_26, "Answer:", 7);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_27, "y", 1);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_28, "yes", 3);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_29, "n", 1);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_30, "no", 2);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_31, " -> [forced ", 12);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_32, "]", 1);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_33, " [", 2);
STRING_LITERAL(TM_JOguTJkl9cZuE2nrrLMMejw_34, "/", 1);
static N_NIMCALL(void, Marker_tyRef_ybQzX9cMrXjEj9bNZNlkjOKg)(void* p, NI op) {
	tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA* a;
	a = (tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*)p;
	nimGCvisit((void*)(*a).warnings.data, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*, newCLI_7309acyOAhDSDzw9ba88Ia1A)(void) {
	tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA* result;
	tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA* T1_;
	nimfr_("newCLI", "cli.nim");
	result = (tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*)0;
	nimln_(48, "cli.nim");
	T1_ = (tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*)0;
	T1_ = (tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*) newObj((&NTI_ybQzX9cMrXjEj9bNZNlkjOKg_), sizeof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA));
	(*T1_).level = ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 1);
	(*T1_).suppressionCount = ((NI) 0);
	(*T1_).showColor = NIM_TRUE;
	(*T1_).suppressMessages = NIM_FALSE;
	result = T1_;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_JOguTJkl9cZuE2nrrLMMejw_6)(void) {
	nimGCvisit((void*)threadCLI_zu7MhEebleCIn6IYLlEuQg, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, maybe_init_cli_Lw25hsj6cTkdNxUweulhgQ)(void) {
	nimfr_("maybe_init_cli", "cli.nim");
	nimln_(58, "cli.nim");
	{
		if (!(threadCLI_zu7MhEebleCIn6IYLlEuQg == NIM_NIL)) goto LA3_;
		nimln_(59, "cli.nim");
		asgnRefNoCycle((void**) (&threadCLI_zu7MhEebleCIn6IYLlEuQg), newCLI_7309acyOAhDSDzw9ba88Ia1A());
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, calculateCategoryOffset_vhBplFmZ5l09cMTyuMBWUAQ)(NimStringDesc* category) {
	NI result;
	NI TM_JOguTJkl9cZuE2nrrLMMejw_8;
	nimfr_("calculateCategoryOffset", "cli.nim");
{	result = (NI)0;
	nimln_(62, "cli.nim");
	{
		if (!!(((category ? category->Sup.len : 0) <= ((NI) 11)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_7));
	}
	LA3_: ;
	nimln_(63, "cli.nim");
	TM_JOguTJkl9cZuE2nrrLMMejw_8 = subInt(((NI) 11), (category ? category->Sup.len : 0));
	result = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_8);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, displayCategory_8gabfQYbrSJGf6bhbE9a2ug)(NimStringDesc* category, tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw displayType, tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig priority) {
	NI offset;
	NimStringDesc* text;
	tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
	nimfr_("displayCategory", "cli.nim");
	nimln_(67, "cli.nim");
	maybe_init_cli_Lw25hsj6cTkdNxUweulhgQ();
	nimln_(70, "cli.nim");
	offset = calculateCategoryOffset_vhBplFmZ5l09cMTyuMBWUAQ(category);
	nimln_(73, "cli.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	nimln_(1136, "strutils.nim");
	T1_[0] = nsuRepeatChar(32, ((NI)chckRange(offset, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	T1_[1] = copyString(category);
	text = nsuFormatOpenArray(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_9), T1_, 2);
	nimln_(74, "cli.nim");
	{
		if (!(*threadCLI_zu7MhEebleCIn6IYLlEuQg).showColor) goto LA4_;
		nimln_(75, "cli.nim");
		{
			nimln_(398, "system.nim");
			nimln_(75, "cli.nim");
			if (!!((priority == ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 0)))) goto LA8_;
			nimln_(76, "cli.nim");
			setForegroundColor_Tw7yxMupneOmAicqiYt3NA(stdout, foregrounds_oX2Nv5KNcGkglUgeHYluAQ[(displayType)- 0], NIM_FALSE);
		}
		LA8_: ;
		nimln_(77, "cli.nim");
		writeStyled_jPzCz3P0CaIFIvdlX9aQd4w(text, styles_1JthzQ2h4VcH4b9cqyYEYPw[(priority)- 0]);
		nimln_(78, "cli.nim");
		resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg();
	}
	goto LA2_;
	LA4_: ;
	{
		nimln_(80, "cli.nim");
		write_c4mGyJBvK73pdM22jiweKQ(stdout, text);
	}
	LA2_: ;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, displayLine_F5zrZ9ax9bfLmb45G31Ablqw)(NimStringDesc* category, NimStringDesc* line, tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw displayType, tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig priority) {
	NimStringDesc* T1_;
	nimfr_("displayLine", "cli.nim");
	nimln_(84, "cli.nim");
	displayCategory_8gabfQYbrSJGf6bhbE9a2ug(category, displayType, priority);
	nimln_(87, "cli.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(line->Sup.len + 1);
appendString(T1_, line);
appendString(T1_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_10));
	writeStyled_jPzCz3P0CaIFIvdlX9aQd4w(T1_, styles_1JthzQ2h4VcH4b9cqyYEYPw[(priority)- 0]);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, display_elIA49aZ9bc7gVVNzTpH3rtw)(NimStringDesc* category, NimStringDesc* msg, tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw displayType, tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig priority) {
	NI i;
	nimfr_("display", "cli.nim");
{	nimln_(91, "cli.nim");
	maybe_init_cli_Lw25hsj6cTkdNxUweulhgQ();
	nimln_(94, "cli.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (*threadCLI_zu7MhEebleCIn6IYLlEuQg).suppressMessages;
		if (!(T4_)) goto LA5_;
		T4_ = (((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1) <= displayType);
		LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		nimln_(95, "cli.nim");
		T3_ = ((*threadCLI_zu7MhEebleCIn6IYLlEuQg).level == ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		LA6_: ;
		if (!T3_) goto LA7_;
		nimln_(96, "cli.nim");
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(99, "cli.nim");
	{
		if (!(priority < (*threadCLI_zu7MhEebleCIn6IYLlEuQg).level)) goto LA11_;
		nimln_(100, "cli.nim");
		{
			NI TM_JOguTJkl9cZuE2nrrLMMejw_11;
			nimln_(398, "system.nim");
			nimln_(100, "cli.nim");
			if (!!((priority == ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 0)))) goto LA15_;
			nimln_(101, "cli.nim");
			TM_JOguTJkl9cZuE2nrrLMMejw_11 = addInt((*threadCLI_zu7MhEebleCIn6IYLlEuQg).suppressionCount, ((NI) 1));
			(*threadCLI_zu7MhEebleCIn6IYLlEuQg).suppressionCount = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_11);
		}
		LA15_: ;
		nimln_(102, "cli.nim");
		goto BeforeRet_;
	}
	LA11_: ;
	nimln_(105, "cli.nim");
	i = ((NI) 0);
	{
		NimStringDesc* line;
		NI first;
		NI last;
		line = (NimStringDesc*)0;
		nimln_(776, "strutils.nim");
		first = ((NI) 0);
		nimln_(777, "strutils.nim");
		last = ((NI) 0);
		{
			nimln_(778, "strutils.nim");
			while (1) {
				NI TM_JOguTJkl9cZuE2nrrLMMejw_13;
				{
					nimln_(779, "strutils.nim");
					while (1) {
						NI TM_JOguTJkl9cZuE2nrrLMMejw_12;
						nimln_(1212, "system.nim");
						nimln_(779, "strutils.nim");
						if ((NU)(last) > (NU)(msg->Sup.len)) raiseIndexError();
						if (!!((((NU8)(msg->data[last])) == ((NU8)(0)) || ((NU8)(msg->data[last])) == ((NU8)(13)) || ((NU8)(msg->data[last])) == ((NU8)(10))))) goto LA21;
						TM_JOguTJkl9cZuE2nrrLMMejw_12 = addInt(last, ((NI) 1));
						last = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_12);
					} LA21: ;
				}
				nimln_(780, "strutils.nim");
				TM_JOguTJkl9cZuE2nrrLMMejw_13 = subInt(last, ((NI) 1));
				line = copyStrLast(msg, first, (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_13));
				{
					NimStringDesc* T27_;
					NI TM_JOguTJkl9cZuE2nrrLMMejw_15;
					nimln_(107, "cli.nim");
					{
						if (!((line ? line->Sup.len : 0) == ((NI) 0))) goto LA25_;
						goto LA22;
					}
					LA25_: ;
					nimln_(108, "cli.nim");
					T27_ = (NimStringDesc*)0;
					{
						if (!(i == ((NI) 0))) goto LA30_;
						T27_ = copyString(category);
					}
					goto LA28_;
					LA30_: ;
					{
						T27_ = copyString(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_14));
					}
					LA28_: ;
					displayLine_F5zrZ9ax9bfLmb45G31Ablqw(T27_, line, displayType, priority);
					nimln_(109, "cli.nim");
					TM_JOguTJkl9cZuE2nrrLMMejw_15 = addInt(i, ((NI) 1));
					i = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_15);
				} LA22: ;
				nimln_(782, "strutils.nim");
				{
					NI TM_JOguTJkl9cZuE2nrrLMMejw_16;
					if ((NU)(last) > (NU)(msg->Sup.len)) raiseIndexError();
					if (!((NU8)(msg->data[last]) == (NU8)(10))) goto LA35_;
					TM_JOguTJkl9cZuE2nrrLMMejw_16 = addInt(last, ((NI) 1));
					last = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_16);
				}
				goto LA33_;
				LA35_: ;
				{
					NI TM_JOguTJkl9cZuE2nrrLMMejw_17;
					nimln_(783, "strutils.nim");
					if ((NU)(last) > (NU)(msg->Sup.len)) raiseIndexError();
					if (!((NU8)(msg->data[last]) == (NU8)(13))) goto LA38_;
					nimln_(784, "strutils.nim");
					TM_JOguTJkl9cZuE2nrrLMMejw_17 = addInt(last, ((NI) 1));
					last = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_17);
					nimln_(785, "strutils.nim");
					{
						NI TM_JOguTJkl9cZuE2nrrLMMejw_18;
						if ((NU)(last) > (NU)(msg->Sup.len)) raiseIndexError();
						if (!((NU8)(msg->data[last]) == (NU8)(10))) goto LA42_;
						TM_JOguTJkl9cZuE2nrrLMMejw_18 = addInt(last, ((NI) 1));
						last = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_18);
					}
					LA42_: ;
				}
				goto LA33_;
				LA38_: ;
				{
					nimln_(786, "strutils.nim");
					goto LA18;
				}
				LA33_: ;
				nimln_(787, "strutils.nim");
				first = last;
			}
		} LA18: ;
	}
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, displayDebug_IV2tE9cOAkZZXLKBePZUCQg)(NimStringDesc* category, NimStringDesc* msg) {
	nimfr_("displayDebug", "cli.nim");
	nimln_(113, "cli.nim");
	display_elIA49aZ9bc7gVVNzTpH3rtw(category, msg, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 2), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 0));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, displayDebug_ZniuJ2GtraBfb5W0ruIkVw)(NimStringDesc* msg) {
	nimfr_("displayDebug", "cli.nim");
	nimln_(117, "cli.nim");
	displayDebug_IV2tE9cOAkZZXLKBePZUCQg(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_19), msg);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, displayTip_Lw25hsj6cTkdNxUweulhgQ_2)(void) {
	nimfr_("displayTip", "cli.nim");
	nimln_(120, "cli.nim");
	maybe_init_cli_Lw25hsj6cTkdNxUweulhgQ();
	nimln_(123, "cli.nim");
	{
		NimStringDesc* msg;
		NimStringDesc* T5_;
		if (!(((NI) 0) < (*threadCLI_zu7MhEebleCIn6IYLlEuQg).suppressionCount)) goto LA3_;
		nimln_(124, "cli.nim");
		nimln_(125, "cli.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = nimIntToStr((*threadCLI_zu7MhEebleCIn6IYLlEuQg).suppressionCount);
		msg = nsuFormatSingleElem(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_20), T5_);
		nimln_(126, "cli.nim");
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_21), msg, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, prompt_rEJhBlhpUUtRqzlsDY1k6g)(tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ forcePrompts, NimStringDesc* question) {
	NIM_BOOL result;
	nimfr_("prompt", "cli.nim");
{	result = (NIM_BOOL)0;
	nimln_(129, "cli.nim");
	switch (forcePrompts) {
	case ((tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ) 1):
	{
		NimStringDesc* T2_;
		nimln_(131, "cli.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = rawNewString(question->Sup.len + 16);
appendString(T2_, question);
appendString(T2_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_23));
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T2_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(132, "cli.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ) 2):
	{
		NimStringDesc* T4_;
		nimln_(134, "cli.nim");
		T4_ = (NimStringDesc*)0;
		T4_ = rawNewString(question->Sup.len + 15);
appendString(T4_, question);
appendString(T4_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_24));
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T4_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(135, "cli.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ) 0):
	{
		NimStringDesc* T6_;
		NimStringDesc* yn;
		NimStringDesc* T7_;
		nimln_(137, "cli.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(question->Sup.len + 6);
appendString(T6_, question);
appendString(T6_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_25));
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T6_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(138, "cli.nim");
		displayCategory_8gabfQYbrSJGf6bhbE9a2ug(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_26), ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(139, "cli.nim");
		yn = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
		nimln_(140, "cli.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = nsuNormalize(yn);
		if (eqStrings(T7_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_27))) goto LA8_;
		if (eqStrings(T7_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_28))) goto LA8_;
		if (eqStrings(T7_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_29))) goto LA9_;
		if (eqStrings(T7_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_30))) goto LA9_;
		goto LA10_;
		LA8_: ;
		{
			nimln_(142, "cli.nim");
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		goto LA11_;
		LA9_: ;
		{
			nimln_(144, "cli.nim");
			result = NIM_FALSE;
			goto BeforeRet_;
		}
		goto LA11_;
		LA10_: ;
		{
			nimln_(146, "cli.nim");
			result = NIM_FALSE;
			goto BeforeRet_;
		}
		LA11_: ;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, promptCustom_NZBEV3Zh0VsRxKiive9aWgQ)(tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ forcePrompts, NimStringDesc* question, NimStringDesc* default_0) {
	NimStringDesc* result;
	nimfr_("promptCustom", "cli.nim");
{	result = (NimStringDesc*)0;
	nimln_(149, "cli.nim");
	switch (forcePrompts) {
	case ((tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ) 1):
	{
		NimStringDesc* T2_;
		nimln_(151, "cli.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = rawNewString(question->Sup.len + default_0->Sup.len + 13);
appendString(T2_, question);
appendString(T2_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_31));
appendString(T2_, default_0);
appendString(T2_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_32));
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T2_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(153, "cli.nim");
		result = copyString(default_0);
		goto BeforeRet_;
	}
	break;
	default:
	{
		nimln_(155, "cli.nim");
		{
			NimStringDesc* user;
			if (!((default_0) && (default_0)->Sup.len == 0)) goto LA6_;
			nimln_(156, "cli.nim");
			display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), question, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
			nimln_(157, "cli.nim");
			displayCategory_8gabfQYbrSJGf6bhbE9a2ug(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_26), ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
			nimln_(158, "cli.nim");
			user = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
			nimln_(159, "cli.nim");
			{
				if (!((user ? user->Sup.len : 0) == ((NI) 0))) goto LA10_;
				result = promptCustom_NZBEV3Zh0VsRxKiive9aWgQ(forcePrompts, question, default_0);
				goto BeforeRet_;
			}
			goto LA8_;
			LA10_: ;
			{
				nimln_(160, "cli.nim");
				result = copyString(user);
				goto BeforeRet_;
			}
			LA8_: ;
		}
		goto LA4_;
		LA6_: ;
		{
			NimStringDesc* T14_;
			NimStringDesc* user_2;
			nimln_(162, "cli.nim");
			T14_ = (NimStringDesc*)0;
			T14_ = rawNewString(question->Sup.len + default_0->Sup.len + 3);
appendString(T14_, question);
appendString(T14_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_33));
appendString(T14_, default_0);
appendString(T14_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_32));
			display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T14_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
			nimln_(163, "cli.nim");
			displayCategory_8gabfQYbrSJGf6bhbE9a2ug(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_26), ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
			nimln_(164, "cli.nim");
			user_2 = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
			nimln_(165, "cli.nim");
			{
				if (!((user_2) && (user_2)->Sup.len == 0)) goto LA17_;
				result = copyString(default_0);
				goto BeforeRet_;
			}
			goto LA15_;
			LA17_: ;
			{
				nimln_(166, "cli.nim");
				result = copyString(user_2);
				goto BeforeRet_;
			}
			LA15_: ;
		}
		LA4_: ;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, promptCustom_zFHrbyrtNEPjp9ba7Hi6rZw)(NimStringDesc* question, NimStringDesc* default_0) {
	NimStringDesc* result;
	nimfr_("promptCustom", "cli.nim");
{	result = (NimStringDesc*)0;
	nimln_(169, "cli.nim");
	result = promptCustom_NZBEV3Zh0VsRxKiive9aWgQ(((tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ) 0), question, default_0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, promptList_5gAXhc5LjOBogWUPyn3jWA)(tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ forcePrompts, NimStringDesc* question, NimStringDesc** args, NI argsLen_0) {
	NimStringDesc* result;
	nimfr_("promptList", "cli.nim");
{	result = (NimStringDesc*)0;
	nimln_(172, "cli.nim");
	switch (forcePrompts) {
	case ((tyEnum_ForcePrompt_6OkmNMWXZdma9bf3IxmvPBQ) 1):
	{
		NimStringDesc* T2_;
		nimln_(174, "cli.nim");
		if ((NU)(((NI) 0)) >= (NU)(argsLen_0)) raiseIndexError();
		result = copyString(args[((NI) 0)]);
		nimln_(175, "cli.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = rawNewString(question->Sup.len + result->Sup.len + 13);
appendString(T2_, question);
appendString(T2_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_31));
appendString(T2_, result);
appendString(T2_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_32));
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T2_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
	}
	break;
	default:
	{
		NimStringDesc* T4_;
		NimStringDesc* T5_;
		nimln_(178, "cli.nim");
		T4_ = (NimStringDesc*)0;
		T5_ = (NimStringDesc*)0;
		T5_ = nsuJoinSep(args, argsLen_0, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_34));
		T4_ = rawNewString(question->Sup.len + T5_->Sup.len + 3);
appendString(T4_, question);
appendString(T4_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_33));
appendString(T4_, T5_);
appendString(T4_, ((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_32));
		display_elIA49aZ9bc7gVVNzTpH3rtw(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_22), T4_, ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(179, "cli.nim");
		displayCategory_8gabfQYbrSJGf6bhbE9a2ug(((NimStringDesc*) &TM_JOguTJkl9cZuE2nrrLMMejw_26), ((tyEnum_DisplayType_DV5lGQyPiU9b7zpmYii6dIw) 1), ((tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig) 3));
		nimln_(180, "cli.nim");
		result = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
		{
			NimStringDesc* arg;
			NI i;
			arg = (NimStringDesc*)0;
			nimln_(2185, "system.nim");
			i = ((NI) 0);
			{
				nimln_(2186, "system.nim");
				while (1) {
					NI TM_JOguTJkl9cZuE2nrrLMMejw_35;
					if (!(i < argsLen_0)) goto LA8;
					nimln_(2187, "system.nim");
					if ((NU)(i) >= (NU)(argsLen_0)) raiseIndexError();
					arg = args[i];
					nimln_(182, "cli.nim");
					{
						NI T11_;
						T11_ = (NI)0;
						T11_ = nsuCmpIgnoreCase(arg, result);
						if (!(T11_ == ((NI) 0))) goto LA12_;
						nimln_(183, "cli.nim");
						result = copyString(arg);
						goto BeforeRet_;
					}
					LA12_: ;
					nimln_(2188, "system.nim");
					TM_JOguTJkl9cZuE2nrrLMMejw_35 = addInt(i, ((NI) 1));
					i = (NI)(TM_JOguTJkl9cZuE2nrrLMMejw_35);
				} LA8: ;
			}
		}
		nimln_(184, "cli.nim");
		result = promptList_5gAXhc5LjOBogWUPyn3jWA(forcePrompts, question, args, argsLen_0);
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setVerbosity_Oyc7NfoFVBC8BaTDuMeUeg)(tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig level) {
	nimfr_("setVerbosity", "cli.nim");
	nimln_(187, "cli.nim");
	(*threadCLI_zu7MhEebleCIn6IYLlEuQg).level = level;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setShowColor_xZJghI4p8WoXA4wzL6Z9bng)(NIM_BOOL val) {
	nimfr_("setShowColor", "cli.nim");
	nimln_(190, "cli.nim");
	(*threadCLI_zu7MhEebleCIn6IYLlEuQg).showColor = val;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setSuppressMessages_xZJghI4p8WoXA4wzL6Z9bng_2)(NIM_BOOL val) {
	nimfr_("setSuppressMessages", "cli.nim");
	nimln_(193, "cli.nim");
	(*threadCLI_zu7MhEebleCIn6IYLlEuQg).suppressMessages = val;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, watchman_cliInit000)(void) {
	nimfr_("cli", "cli.nim");
nimRegisterThreadLocalMarker(TM_JOguTJkl9cZuE2nrrLMMejw_6);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, watchman_cliDatInit000)(void) {
static TNimNode* TM_JOguTJkl9cZuE2nrrLMMejw_2[5];
static TNimNode* TM_JOguTJkl9cZuE2nrrLMMejw_3[4];
NI TM_JOguTJkl9cZuE2nrrLMMejw_5;
static char* NIM_CONST TM_JOguTJkl9cZuE2nrrLMMejw_4[4] = {
"DebugPriority", 
"LowPriority", 
"MediumPriority", 
"HighPriority"};
static TNimNode TM_JOguTJkl9cZuE2nrrLMMejw_0[11];
NTI_jDewjhp9a60tOuoQbdqvxBA_.size = sizeof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA);
NTI_jDewjhp9a60tOuoQbdqvxBA_.kind = 18;
NTI_jDewjhp9a60tOuoQbdqvxBA_.base = 0;
NTI_jDewjhp9a60tOuoQbdqvxBA_.flags = 2;
TM_JOguTJkl9cZuE2nrrLMMejw_2[0] = &TM_JOguTJkl9cZuE2nrrLMMejw_0[1];
NTI_4B6X6c5gq8OV1pR0JsF1ig_.size = sizeof(tyEnum_Priority_4B6X6c5gq8OV1pR0JsF1ig);
NTI_4B6X6c5gq8OV1pR0JsF1ig_.kind = 14;
NTI_4B6X6c5gq8OV1pR0JsF1ig_.base = 0;
NTI_4B6X6c5gq8OV1pR0JsF1ig_.flags = 3;
for (TM_JOguTJkl9cZuE2nrrLMMejw_5 = 0; TM_JOguTJkl9cZuE2nrrLMMejw_5 < 4; TM_JOguTJkl9cZuE2nrrLMMejw_5++) {
TM_JOguTJkl9cZuE2nrrLMMejw_0[TM_JOguTJkl9cZuE2nrrLMMejw_5+2].kind = 1;
TM_JOguTJkl9cZuE2nrrLMMejw_0[TM_JOguTJkl9cZuE2nrrLMMejw_5+2].offset = TM_JOguTJkl9cZuE2nrrLMMejw_5;
TM_JOguTJkl9cZuE2nrrLMMejw_0[TM_JOguTJkl9cZuE2nrrLMMejw_5+2].name = TM_JOguTJkl9cZuE2nrrLMMejw_4[TM_JOguTJkl9cZuE2nrrLMMejw_5];
TM_JOguTJkl9cZuE2nrrLMMejw_3[TM_JOguTJkl9cZuE2nrrLMMejw_5] = &TM_JOguTJkl9cZuE2nrrLMMejw_0[TM_JOguTJkl9cZuE2nrrLMMejw_5+2];
}
TM_JOguTJkl9cZuE2nrrLMMejw_0[6].len = 4; TM_JOguTJkl9cZuE2nrrLMMejw_0[6].kind = 2; TM_JOguTJkl9cZuE2nrrLMMejw_0[6].sons = &TM_JOguTJkl9cZuE2nrrLMMejw_3[0];
NTI_4B6X6c5gq8OV1pR0JsF1ig_.node = &TM_JOguTJkl9cZuE2nrrLMMejw_0[6];
TM_JOguTJkl9cZuE2nrrLMMejw_0[1].kind = 1;
TM_JOguTJkl9cZuE2nrrLMMejw_0[1].offset = offsetof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA, level);
TM_JOguTJkl9cZuE2nrrLMMejw_0[1].typ = (&NTI_4B6X6c5gq8OV1pR0JsF1ig_);
TM_JOguTJkl9cZuE2nrrLMMejw_0[1].name = "level";
TM_JOguTJkl9cZuE2nrrLMMejw_2[1] = &TM_JOguTJkl9cZuE2nrrLMMejw_0[7];
TM_JOguTJkl9cZuE2nrrLMMejw_0[7].kind = 1;
TM_JOguTJkl9cZuE2nrrLMMejw_0[7].offset = offsetof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA, warnings);
TM_JOguTJkl9cZuE2nrrLMMejw_0[7].typ = (&NTI_OWHFqZn3R9csWXH86N7Rq2g_);
TM_JOguTJkl9cZuE2nrrLMMejw_0[7].name = "warnings";
TM_JOguTJkl9cZuE2nrrLMMejw_2[2] = &TM_JOguTJkl9cZuE2nrrLMMejw_0[8];
TM_JOguTJkl9cZuE2nrrLMMejw_0[8].kind = 1;
TM_JOguTJkl9cZuE2nrrLMMejw_0[8].offset = offsetof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA, suppressionCount);
TM_JOguTJkl9cZuE2nrrLMMejw_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_JOguTJkl9cZuE2nrrLMMejw_0[8].name = "suppressionCount";
TM_JOguTJkl9cZuE2nrrLMMejw_2[3] = &TM_JOguTJkl9cZuE2nrrLMMejw_0[9];
TM_JOguTJkl9cZuE2nrrLMMejw_0[9].kind = 1;
TM_JOguTJkl9cZuE2nrrLMMejw_0[9].offset = offsetof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA, showColor);
TM_JOguTJkl9cZuE2nrrLMMejw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_JOguTJkl9cZuE2nrrLMMejw_0[9].name = "showColor";
TM_JOguTJkl9cZuE2nrrLMMejw_2[4] = &TM_JOguTJkl9cZuE2nrrLMMejw_0[10];
TM_JOguTJkl9cZuE2nrrLMMejw_0[10].kind = 1;
TM_JOguTJkl9cZuE2nrrLMMejw_0[10].offset = offsetof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA, suppressMessages);
TM_JOguTJkl9cZuE2nrrLMMejw_0[10].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_JOguTJkl9cZuE2nrrLMMejw_0[10].name = "suppressMessages";
TM_JOguTJkl9cZuE2nrrLMMejw_0[0].len = 5; TM_JOguTJkl9cZuE2nrrLMMejw_0[0].kind = 2; TM_JOguTJkl9cZuE2nrrLMMejw_0[0].sons = &TM_JOguTJkl9cZuE2nrrLMMejw_2[0];
NTI_jDewjhp9a60tOuoQbdqvxBA_.node = &TM_JOguTJkl9cZuE2nrrLMMejw_0[0];
NTI_ybQzX9cMrXjEj9bNZNlkjOKg_.size = sizeof(tyObject_CLIcolonObjectType__jDewjhp9a60tOuoQbdqvxBA*);
NTI_ybQzX9cMrXjEj9bNZNlkjOKg_.kind = 22;
NTI_ybQzX9cMrXjEj9bNZNlkjOKg_.base = (&NTI_jDewjhp9a60tOuoQbdqvxBA_);
NTI_ybQzX9cMrXjEj9bNZNlkjOKg_.flags = 2;
NTI_ybQzX9cMrXjEj9bNZNlkjOKg_.marker = Marker_tyRef_ybQzX9cMrXjEj9bNZNlkjOKg;
}

